language: go


sudo: false


env:
  global:
    - PATH=$HOME/gopath/bin:$PATH


go:
  - 1.3
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip


before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover


install:
  - make travis_install


script:
  - make build
  - ./scw version
  - make travis_run
  - make cover
  - goveralls -service=travis-ci -v -coverprofile=profile.out
